security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user_entity:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_entity
            form_login:
                login_path: app_authentication_login
                check_path: app_authentication_login
            logout:
                path: /logout

    access_control:
        - { path: ^/(login|upgrade), roles: PUBLIC_ACCESS }
        - { path: ^/template/send, roles: PUBLIC_ACCESS }
        - { path: ^/settings, roles: ROLE_ADMIN }
        - - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
