parameters:
    upload_directory: '%kernel.project_dir%/public/images/upload'
    upload_directory_video: '%kernel.project_dir%/public/videos/upload'
    domain_name: '%env(DOMAIN_NAME)%'
    database_name: '%env(DATABASE_NAME)%'
    smtp_address: '%env(SMTP_ADDRESS)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    _instanceof:
        App\SMTP\MessageHandler\MessageHandlerInterface:
            tags:
                - { name: 'app.smtp.message_handler' }

    App\Doctrine\Listener\CredentialsInboxListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', entity: 'App\Entity\Inbox', event: 'prePersist' }

    App\Business\SidebarBusiness:
        arguments:
            $directoryConfiguration: '%kernel.project_dir%/config/sidebar'

    App\Doctrine\Listener\PasswordHasherListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', entity: 'App\Entity\User', event: 'prePersist' }
            - { name: 'doctrine.orm.entity_listener', entity: 'App\Entity\User', event: 'preUpdate' }

    App\Doctrine\Listener\ProjectOwnerListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', entity: 'App\Entity\Project', event: 'prePersist' }

    App\Business\ParameterBusiness:
        arguments:
            $defaultConfigurationPath: '%kernel.project_dir%/config/parameters.yaml'
            $userConfigurationPath: '%env(resolve:USER_CONFIGURATION_PATH)%'

    Doctrine\Migrations\DependencyFactory: '@doctrine.migrations.dependency_factory'

    App\Business\UpdateBusiness:
        arguments:
            $updateCode: '%env(UPDATE_CODE)%'

    App\Business\DatabaseBusiness:
        arguments:
            $withoutDatabaseConnection: '@doctrine.dbal.without_database_connection'


when@dev:
    services:
        App\Doctrine\Subscriber\FixtureSubscriber:
            arguments:
                $logger: '@monolog.logger.fixtures'
            tags:
                - { name: doctrine.event_subscriber }

        Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'